# Generated by Django 4.0 on 2022-02-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка на Instagram аккаунт')),
                ('icon', models.ImageField(upload_to='media', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagram',
            },
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка на Telegram аккаунт')),
                ('icon', models.ImageField(upload_to='media', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Telegram',
                'verbose_name_plural': 'Telegram',
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='Ссылка на Twitter аккаунт')),
                ('icon', models.ImageField(upload_to='media', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Twitter',
                'verbose_name_plural': 'Twitter',
            },
        ),
    ]
