# Generated by Django 4.0 on 2022-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_workingwithus_alter_banners_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('keywords', models.TextField(verbose_name='Новость')),
                ('img', models.ImageField(upload_to='media', verbose_name='Фото')),
            ],
        ),
        migrations.AlterModelOptions(
            name='workingwithus',
            options={'verbose_name': 'Партнёра', 'verbose_name_plural': 'Партнёры'},
        ),
    ]
