# Generated by Django 4.0 on 2022-02-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects',
            name='pic',
        ),
        migrations.CreateModel(
            name='ObjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='media', verbose_name='Картинка')),
                ('object', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='objects.objects', verbose_name='Для объекта')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
