# Generated by Django 4.0 on 2022-02-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_remove_objects_pic_objectimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='little_desc',
            field=models.CharField(max_length=300, unique=True, verbose_name='Краткое описание'),
        ),
    ]
