# Generated by Django 4.0 on 2022-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL (Необязательно)'),
        ),
    ]
