# Generated by Django 4.0 on 2022-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(default=0, max_length=100, verbose_name='Цена'),
        ),
    ]
